# Generated by Django 3.1.3 on 2020-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
